// Export all Pages
export { default as PageNotFound } from './404'
export { default as AdminSignup } from './Auth/adminSignup/AdminRegistration'
export { default as ForgotPassword } from './Auth/forgotPassword/ForgotPassword'
export { default as SignIn } from './Auth/login/SignIn'
export { default as Register } from './Auth/studentRegistration/Register'
export { default as StudentSignup } from './Auth/studentSignup/StudentSignup'
export { default as AboutUs } from './Externals/AboutUs'
export { default as Blog } from './Externals/Blog'
export { default as SingleBlogPage } from './Externals/Blog/sections/singleBlogPage'
export { default as ContactUs } from './Externals/ContactUs'
export { default as Development } from './Externals/Development'
export { default as Employers } from './Externals/Employers'
export { default as Faq } from './Externals/Faqs'
export { default as HomePage } from './Externals/Home'
export { default as Intro } from './Externals/Intro'
